"""add started_at and current_phase to auditpointrun

Revision ID: 2f7d9bf5296d
Revises: b136313bb946
Create Date: 2026-05-17 04:23:59.449879
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "2f7d9bf5296d"
down_revision = "b136313bb946"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditpointrun", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("auditpointrun", sa.Column("current_phase", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auditpointrun", "current_phase")
    op.drop_column("auditpointrun", "started_at")
    # ### end Alembic commands ###
