"""add_activity_log_and_actor_fields

Revision ID: b136313bb946
Revises: c29d429d03a0
Create Date: 2026-05-17 00:38:09.365033
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision = "b136313bb946"
down_revision = "c29d429d03a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级：新增 activitylog 表 + auditrun/tenderdoc 两列。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activitylog",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("before_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("after_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("auditrun", sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("tenderdoc", sa.Column("uploaded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级：删除 activitylog 表 + auditrun/tenderdoc 两列。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenderdoc", "uploaded_by")
    op.drop_column("auditrun", "created_by")
    op.drop_table("activitylog")
    # ### end Alembic commands ###
