"""add heartbeat_at to auditrun and extractrun

Revision ID: c29d429d03a0
Revises: 20260427_remove_checkpointdraft
Create Date: 2026-05-14 21:57:46.515664
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "c29d429d03a0"
down_revision = "20260427_remove_checkpointdraft"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditrun", sa.Column("heartbeat_at", sa.DateTime(), nullable=True))
    op.add_column("extractrun", sa.Column("heartbeat_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extractrun", "heartbeat_at")
    op.drop_column("auditrun", "heartbeat_at")
    # ### end Alembic commands ###
