"""add comparerun table

Revision ID: d08dafa25255
Revises: f7a00cce372b
Create Date: 2026-05-24 23:52:02.966051
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "d08dafa25255"
down_revision = "f7a00cce372b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comparerun",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("file_names_json", sa.String(), nullable=True),
        sa.Column("progress_json", sa.String(), nullable=True),
        sa.Column("result_path", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comparerun")
    # ### end Alembic commands ###
