"""add started_at and current_phase to extractrun

Revision ID: f7a00cce372b
Revises: 2f7d9bf5296d
Create Date: 2026-05-17 06:57:28.335619
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "f7a00cce372b"
down_revision = "2f7d9bf5296d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("extractrun", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("extractrun", sa.Column("current_phase", sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractrun', 'current_phase')
    op.drop_column('extractrun', 'started_at')
    # ### end Alembic commands ###

