"""add_password_hash_and_is_active_to_user

Revision ID: f978fd86aeb4
Revises: f7a00cce372b
Create Date: 2026-05-22 18:00:13.953861
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "f978fd86aeb4"
down_revision = "f7a00cce372b"
branch_labels = None
depends_on = None




def upgrade() -> None:
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # 存量用户回填默认值
    op.execute("UPDATE \"user\" SET password_hash = '__no_password__', is_active = 1 WHERE password_hash IS NULL")
    # 改为 NOT NULL
    op.alter_column('user', 'password_hash', nullable=False)
    op.alter_column('user', 'is_active', nullable=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###

